const EErrors = {
    ROUTING_ERROR: 1,
    AUTHENTICATION_ERROR: 2,
    DATABASE_ERROR: 3,
    AUTHORIZATION_ERROR: 4,
    NOT_FOUND_ERROR: 5,
    INTERNAL_SERVER_ERROR: 6,
    INVALID_PRODUCT: 7,
    FAILED_TO_ADD_PRODUCT: 8,
}

export default EErrors;